#ifndef CHESS_ENGINE_BOARDSTATUS_H
#define CHESS_ENGINE_BOARDSTATUS_H

enum BoardStatus { WIN_WHITE, WIN_BLACK, INSUFFICIENT_MATERIAL_BLACK, INSUFFICIENT_MATERIAL_WHITE, IN_PROGRESS, DRAW };

#endif // CHESS_ENGINE_BOARDSTATUS_H
