#ifndef CHESS_ENGINE_PIECES_H
#define CHESS_ENGINE_PIECES_H

enum Pieces {
    KING_WHITE,
    QUEEN_WHITE,
    ROOK_WHITE,
    BISHOP_WHITE,
    KNIGHT_WHITE,
    PAWN_WHITE,
    KING_BLACK,
    QUEEN_BLACK,
    ROOK_BLACK,
    BISHOP_BLACK,
    KNIGHT_BLACK,
    PAWN_BLACK
};

#endif // CHESS_ENGINE_PIECES_H
