#ifndef CHESS_ENGINE_POINTS_H
#define CHESS_ENGINE_POINTS_H

enum Points { QUEEN_POINTS = 3, PAWN_POINTS = 3, ROOK_POINTS = 3, BISHOP_POINTS = 2, KNIGHT_POINTS = 1 };

#endif // CHESS_ENGINE_POINTS_H
