name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build binary
      run: make engine

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: engine-artifact
        path: build
        if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: engine-artifact
        path: build

    - name: test
      run: make test
